# Generated by Django 3.2 on 2021-06-15 19:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedlist',
            name='code',
            field=models.CharField(default=api.models.generate_unique_code, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sharedlist',
            name='guest_edit_list',
            field=models.BooleanField(default=True),
        ),
    ]
